name: 'oidc-github-actions-debugger'
description: 'Print decoded OIDC token claims generated through GitHub Actions (trusted use only).'
inputs:
  audience:
    description: 'The audience to use when requesting the JWT. Your Github server URL and repository owner (e.g. https://github.com/github).'
    required: false
    default: '${{ github.server_url }}/${{ github.repository_owner }}'

runs:
  using: "composite"
  steps:
    - name: Debug OIDC claims
      if: ${{ github.event_name != 'pull_request' && github.event_name != 'pull_request_target' }}
      shell: bash
      env:
        AUDIENCE: "${{ inputs.audience }}"
      run: |
        set -euo pipefail

        TOKEN_JSON="$(curl -fsS \
          -H "Authorization: bearer $ACTIONS_ID_TOKEN_REQUEST_TOKEN" \
          "${ACTIONS_ID_TOKEN_REQUEST_URL}&audience=${AUDIENCE}")"

        ID_TOKEN="$(jq -r '.value' <<<"$TOKEN_JSON")"
        echo "::add-mask::$ID_TOKEN"

        # Decode JWT payload (base64url -> json)
        payload_b64url="$(cut -d. -f2 <<<"$ID_TOKEN")"
        payload_b64="$(tr '_-' '/+' <<<"$payload_b64url")"

        # add base64 padding
        case $((${#payload_b64} % 4)) in
          2) payload_b64="${payload_b64}==";;
          3) payload_b64="${payload_b64}=";;
          0) :;;
          *) echo "Invalid base64 length" >&2; exit 1;;
        esac

        echo "$payload_b64" | base64 -d | jq
